---
registry:
  - namespace:
      - :brokers
    features:
      - key: :brokers
        is_enabled: true
        meta:
          label: Brokers
          content_type: :boolean
          default: true
          description: The Enroll Application provides a dashboard for brokers where they may access and manage client employers and their employees. A brokerâ€™s account allows the broker to see all of his or her small group and individual clients. The broker is able to access employer, employee, and individual accounts from the dashboard.
          is_required: true
          is_visible: true
        settings:
          - key: :carrier_appointments
            item: {"Anthem Blue Cross and Blue Shield": nil, "Community Health Options": nil, "Harvard Pilgrim Health Care":  nil, "Northeast Delta Dental": nil, "Renaissance Dental": nil} # Should be a hash with the carrier name as a string and the value as nil
      - key: :broker_attestation_fields
        item: :broker_attestation_fields
        is_enabled: true
      - key: :allow_alphanumeric_npn
        item: :allow_alphanumeric_npn
        is_enabled: true
      - key: :broker_training_link
        is_enabled: true
        item: "https://ideacrew.inquisiqlms.com/"
      - key: broker_agreement_url
        is_enabled: true
        item: "https://ideacrew.com/brokeragreement"
      - key: :allow_edit_broker_email
        is_enabled: <%= ENV['ALLOW_EDIT_BROKER_EMAIL_IS_ENABLED'] || false %>
      - key: :allow_edit_broker_npn
        is_enabled: <%= ENV['ALLOW_EDIT_BROKER_NPN_IS_ENABLED'] || false %>
      - key: :send_broker_hired_event_to_edi
        is_enabled: <%= ENV['BROKER_HIRED_EVENT_TO_EDI_IS_ENABLED'] || true %>
      - key: :send_broker_fired_event_to_edi
        is_enabled: <%= ENV['BROKER_FIRED_EVENT_TO_EDI_IS_ENABLED'] || true %>
      # Enhancements for Brokers acting as consumers under the same account
      - key: :broker_role_consumer_enhancement
        is_enabled: <%= ENV['BROKER_ROLE_CONSUMER_ENHANCEMENT_IS_ENABLED'] || false %>
