---
registry:
  - namespace:
    - :enroll_app
    - :aca_individual_market
    features:
      - key: :residency_self_attestation
        item: :residency_attestation
        is_enabled: true
        settings:
          - key: :effective_period
            item: <%= Date.new(2020,6,6)..Date.new(2020,9,15) %>
      - key: :verification_sensitive_attributes
        item: :consumer_role_hub_call
        is_enabled: true
        settings:
          - key: :demographic_attributes
            item: ['first_name', 'last_name', 'ssn', 'us_citizen', 'naturalized_citizen', 'eligible_immigration_status', 'dob']
      - key: :special_enrollment_period
        is_enabled: true
        settings:
          - key: :individual_market_monthly_enrollment_due_on
            item: 15
