---
registry:
  - namespace:
    - :enroll_app
    - :aca_individual_market
    features:
      - key: :residency_self_attestation
        item: :residency_attestation
        is_enabled: true
        settings:
          - key: :effective_period
            item: <%= Date.new(2020,6,6)..Date.new(2020,9,15) %>
