---
registry:
  - namespace:
    - :enroll_app
    - :aca_individual_market
    features:
      - key: :financial_assistance
        is_enabled: true
  - namespace:
    - :enroll_app
    - :aca_individual_market
    - :financial_assistance
    features:
      - key: :faa_ext_service
        is_enabled: true
        settings:
          - key: :aceds_curam
            item: false
          - key: :ivl_application_checklist
            item: 'IVL_Application_Checklist_Final_02172021.pdf'
      - key: :indian_health_service_question
        is_enabled: false
      - key: :mainecare_healthcare_questions
        is_enabled: true
