assertion_consumer_service_url: "<%= ENV['ASSERTION_CONSUMER_SERVICE_URL'] %>"
assertion_consumer_logout_service_url: "<%= ENV['ASSERTION_CONSUMER_SERVICE_LOGOUT_URL'] %>"
issuer: "<%= ENV['SAML_ISSUER'] %>"
idp_entity_id: "<%= ENV['IDP_ENTITY_ID'] %>"
idp_sso_target_url: "<%= ENV['IDP_SSO_TARGET_URL'] %>"
idp_slo_target_url:  "<%= ENV['IDP_SLO_TARGET_URL'] %>"
idp_cert:  "<%= ENV['IDP_CERTIFICATE'] %>"
name_identifier_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
idp_cert_fingerprint:  "<%= ENV['IDP_CERT_FINGERPRINT'] %>"
idp_cert_fingerprint_algorithm: "http://www.w3.org/2000/09/xmldsig#sha1"
curam_landing_page_url: "<%= ENV['LANDING_PAGE_URL'] %>"
saml_logout_url: "<%= ENV['LOGOUT_URL'] %>"
account_conflict_url: "<%= ENV['ACCOUNT_CONFLICT_URL'] %>"
account_recovery_url: "<%= ENV['ACCOUNT_RECOVERY_URL'] %>"
iam_login_url: "<%= ENV['LOGIN_URL'] %>"
curam_broker_dashboard: "<%= ENV['BROKER_DASHBOARD_URL'] %>"
pay_now_issuer: "<%= ENV['PAY_NOW_ISSUER'] %>"
pay_now_private_key_location: "<%= ENV['PAY_NOW_PRIV_KEY_LOCATION'] %>"
pay_now_x509_cert_location: "<%= ENV['PAY_NOW_PUB_KEY_LOCATION'] %>"
kaiser_pay_now_url: "<%= ENV['PAY_NOW_URL'] || 'https://' %>"
kaiser_pay_now_audience: "<%= ENV['PAY_NOW_AUDIENCE'] || 'https://' %>"
kaiser_pay_now_relay_state: "<%= ENV['PAY_NOW_RELAY_STATE'] || 'https://' %>"
delta_dental_pay_now_url: "https://"
delta_dental_pay_now_audience: "https://"
delta_dental_pay_now_relay_state: "https://"
dentegra_pay_now_url: "https://"
dentegra_pay_now_audience: "https://"
dentegra_pay_now_relay_state: "https://"
dominion_national_pay_now_url: "https://"
dominion_national_pay_now_audience: "https://"
dominion_national_pay_now_relay_state: "https://"
best_life_pay_now_url: "https://"
best_life_pay_now_audience: "https://"
best_life_pay_now_relay_state: "https://"
metlife_pay_now_url: "https://"
metlife_pay_now_audience: "https://"
metlife_pay_now_relay_state: "https://"
carefirst_pay_now_url: "https://"
carefirst_pay_now_audience: "https://"
carefirst_pay_now_relay_state: "https://"
aetna_pay_now_url: "https://"
aetna_pay_now_audience: "https://"
aetna_pay_now_relay_state: "https://"
unitedhealthcare_pay_now_url: "https://"
unitedhealthcare_pay_now_audience: "https://"
unitedhealthcare_pay_now_relay_state: "https://"
northeast_delta_dental_pay_now_url: "<%= ENV['NEDD_PAY_NOW_URL'] %>"
northeast_delta_dental_pay_now_audience: "<%= ENV['NEDD_PAY_NOW_URL'] %>"
northeast_delta_dental_pay_now_relay_state: "<%= ENV['NEDD_PAY_NOW_URL'] %>"
anthem_blue_cross_and_blue_shield_pay_now_url: "<%= ENV['ANTHEM_PAY_NOW_URL'] %>"
anthem_blue_cross_and_blue_shield_pay_now_audience: "<%= ENV['ANTHEM_PAY_NOW_URL'] %>"
anthem_blue_cross_and_blue_shield_pay_now_relay_state: "<%= ENV['ANTHEM_PAY_NOW_URL'] %>"
harvard_pilgrim_health_care_pay_now_url: "<%= ENV['HPHC_PAY_NOW_URL'] %>"
harvard_pilgrim_health_care_pay_now_audience: "<%= ENV['HPHC_PAY_NOW_URL'] %>"
harvard_pilgrim_health_care_pay_now_relay_state: "<%= ENV['HPHC_PAY_NOW_URL'] %>"
community_health_options_pay_now_url: "<%= ENV['CHO_PAY_NOW_URL'] %>"
community_health_options_pay_now_audience: "<%= ENV['CHO_PAY_NOW_URL'] %>"
community_health_options_pay_now_relay_state: "<%= ENV['CHO_PAY_NOW_URL'] %>"
