---
registry:
  - namespace:
      - :features
    features:
      - key: :enroll_app
        is_enabled: true
        meta:
          label: Enroll Application
          content_type: :boolean
          default: true
          description: The Enroll Application enables customers to register and enroll in products, including determining eligibility, shopping for products, calculating premiums, and securely managing their personal information
          is_required: true
          is_visible: true
        settings:
          - key: :application_name
            item: "enroll_dc"
          - key: :copyright_period_start
            item: ""
          - key: :policies_url
            item: ""
          - key: :faqs_url
            item: ""
          - key: :help_url
            item: "https://www.coverme.gov/help/"
          - key: :business_resource_center_url
            item: ""
          - key: :nondiscrimination_notice_url
            item: ""
          - key: :submit_docs_url
            item: ""
          - key: :site_key
            item: :me
          - key: :state_abbreviation
            item: "ME"
          - key: :subdomain
            item: "cme"
          - key: :domain_name
            item: "cme.enroll.openhbx.org"
          - key: :site_title
            item: "Maine Cover ME"
          - key: :home_url
            item: "https://cme.enroll.openhbx.org/"
          - key: :home_business_url
            item: "https://www.accesshealthct.com/AHCT/LandingPageCTHIX"
          - key: :help_url
            item: "https://www.coverme.gov/help/"
          - key: :main_web_address_url
            item: "https://www.coverme.gov"
          - key: :invoice_bill_url
            item: ""
          - key: :payment_pdf_url
            item: "pdf/employers_paying_your_premiums_online.pdf"
          - key: :user_sign_in_url
            item: "https://www.accesshealthct.com/AHCT/LandingPageCTHIX"
          - key: :website_name
            item: "https://www.accesshealthct.com/AHCT/LandingPageCTHIX"
          - key: :main_web_address
            item: "https://www.accesshealthct.com/AHCT/LandingPageCTHIX"
          - key: :website_name
            item: "https://www.coverme.gov"
          - key: :main_web_address
            item: "https://www.coverme.gov"
          - key: :health_care_website
            item: "www.healthcare.gov"
          - key: :health_care_website_url
            item: "https://www.healthcare.gov"
          - key: :short_name
            item: "Maine Cover ME"
          - key: :byline
            item: "Maine's Official Health Insurance Marketplace"
          - key: :long_name
            item: "Maine Cover ME"
          - key: :header_message
            item: "Maine's Official Health Insurance Marketplace"
          - key: :byline
            item: "Welcome to Maine's Health Insurance Marketplace"
          - key: :logo_file_name
            item: "logo.png"
          - key: :make_their_premium_payments_online
            item: ""
          - key: :tab_icon
            item: "favicon.ico"
          - key: :employer_application_deadline_link
            item: ""
          - key: :s3_prefix
            item: "mehbx"
          - key: :broker_quoting_enabled
            item: false
          - key: :broker_claim_quoting_enabled
            item: true
          - key: :guidance_for_business_owners_url
            item: ""
          - key: :use_default_devise_path
            item: true
          - key: :plan_options_title_for_ma
            item: true
          - key: :create_routes
            item: ["/insured/employee/privacy", "/employers/employer_profiles/new", "/insured/consumer_role/privacy"]
          - key: :sign_in_routes
            item: ["/families/home"]
          - key: :shop_find_your_doctor_url
            item: ""
          - key: :document_verification_checklist_url
            item: ""
          - key: :terms_and_conditions_url
            item: ""
          - key: :certification_url
            item: ""
          - key: :document_verification_checklist_url
            item: ""
          - key: :terms_and_conditions_url
            item: ""
          - key: :certification_url
            item: ""
          - key: :registration_path
            item: ""
          - key: :broker_registration_path
            item: ""
          - key: :broker_registration_guide
            item: ""
          - key: :home_forms_url
            item: ""
          - key: :forms_name
            item: ""
          - key: :forms
            item: ""
            item: ""
          - key: :forms_name
            item: ""
          - key: :short_url
            item: ""
          - key: :forms
            item: ""
          - key: :website_url
            item: "www.healthcare.gov"
          - key: :healthcare_name
            item: "www.healthcare.gov"
          - key: :healthcare_url
            item: "https://www.healthcare.gov/"
          - key: :irs_url
            item: "https://www.irs.gov/"
          - key: :exchange_hbx_id
            item: "ME0"
          - key: :mail_address
            item: "info@coverme.gov"
          - key: :no_reply_email
            item: "noreply@coverme.gov"
          - key: :mail_address
            item: "info@coverme.gov"
          - key: :producer_email_address
            item: 'mehl.producer@coverme.gov'
          - key: :privacy_policy
            item: ""
          - key: :no_reply_email
            item: "noreply@coverme.gov"
          - key: :producer_email_address
            item: ''
          - key: :privacy_policy
            item: ""
          - key: :late_rates_message
            item: "Due to a delay, premiums for some coverage effective dates are not available yet. Please check again soon to see if this information has been updated. You can also contact Customer Service or your broker if you need help."
          - key: :faa_enabled
            item: false
          - key: :ivl_responsibility_url
            item: ""
          - key: :curam_enabled?
            item: true
          - key: :support_for_ie_browser
            item: true
          - key: :block_ie_browser
            item: false
          - key: :block_ie_browser_after
            item: Mon, 01 Jun 2020
          - key: :publisher
            item: "dchl"
          - key: :prod_tax_info
            item: ""
          - key: :staging_tax_info_url
            item: ""
          - key: :statewide_area
            item: "Maine"
          - key: :exchange_name
            item: "Cover ME Health Benefit Exchange"
          - key: :state_long_title
            item: "the state of Maine"
          - key: :state_dmv_link
            item: "https://www.maine.gov/sos/bmv/"
          - key: :contact_center_po_box
            item: "PO Box 97022"
          - key: :contact_center_state_and_city
            item: "Augusta, ME"
          - key: :contact_center_zip_code
            item: "04330"
          - key: :contact_center_email_address
            item: "smallbusiness@coverme.gov"
          - key: :social_media
            item: ''
          - key: :health_benefit_exchange_authority_phone_number
            item: "1-800-965-7476"
          - key: :contact_center_name
            item: "Cover ME's Customer Care Center"
          - key: :contact_center_short_number
            item: "(855) 532-5465"
          - key: :producer_advisory_committee_url
            item: ""
          - key: :mailer_logo_file_name
            item: "coverme.jpg"
          - key: :broker_course_administering_organization_number
            item: '(877) 880-1335'
          - key: :broker_course_administering_organization
            item: "NAHU"
          - key: :broker_course_administering_organization_link
            item: 'https://nahu.inreachce.com/Details?resultsPage=1&sortBy=&q=dc+broker&searchType=1&groupId=154ae22b-92eb-41f0-854b-3a9cabc20c8e'
          - key: :privacy_url
            item: "https://www.dchealthlink.com/privacy"
          - key: :privacy_act_statement
            item: ""
          - key: :site_broker_attestation_link
            item: ""
          - key: :rating_areas
            item: "single"
      - key: :pay_now_functionality
        item: "kaiser_enabled"
        is_enabled: true
        settings:
        - key: :carriers
          item: 'Kaiser'
        - key: :carriers_long_name
          item: 'Kaiser Permanante'
        - key: :carriers_registration_website
          item: "https://healthy.kaiserpermanente.org/new-members/#register-to-kp-org"
      - key: :agency_staff
        item: :agency_staff
        is_enabled: false
      - key: :send_secure_message_family
        item: :send_secure_message
        is_enabled: true
      - key: :sep_carousel_message
        item: :sep_carousel
        is_enabled: true
        settings:
          - key: :effective_period
            item: <%= Date.new(2020,9,18)..Date.new(2021,3,31) %>
      - key: :special_cover_header
        item: "special_cover_header"
        is_enabled: false
        settings: 
          - key: :filename
            item: "CoverME_WebsiteHeader_01.jpg"
  - namespace:
      - :features
      - :enroll_app
      - :aca_shop
    features:
      - key: :aca_shop_dependent_age_off
        item: Operations::Shop::DependentAgeOff.new
        is_enabled: true
        settings:
          - key: :period
            item: :annual
          - key: :cut_off_age
            item: 26
          - key: :relationship_kinds
            item: ['child', 'ward', 'foster_child', 'adopted_child']
      - key: :aca_fehb_dependent_age_off
        item: Operations::Fehb::DependentAgeOff.new
        is_enabled: true
        settings:
          - key: :period
            item: :monthly
          - key: :cut_off_age
            item: 26
          - key: :relationship_kinds
            item: ['child', 'ward', 'foster_child', 'adopted_child']
      - key: :aca_individual_dependent_age_off
        item: Operations::Individual::DependentAgeOff.new
        is_enabled: true
        settings:
          - key: :period
            item: :annual
          - key: :cut_off_age
            item: 26
          - key: :relationship_kinds
            item: ['child', 'ward', 'foster_child', 'adopted_child']
      - key: :age_off_relaxed_eligibility
        item: Operations::AgeOffRelaxedEligibility.new
        is_enabled: true
      - key: :display_cost_warning_message
        is_enabled: false
      - key: employee_datable_waiver_bulk_actions
        is_enabled: false
