---
registry:
  - namespace:
      - :fdsh_services
    features:
      - key: :ridp_h139
        is_enabled: true
      - key: :paper_application_verification
        is_enabled: false
      - key: :vlp_h92
        is_enabled: true
