---
registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    features:
      - key: :aca_shop_osse_eligibility
        item: :aca_shop_osse_eligibility
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_IS_ENABLED'] || false %>
  
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :aca_shop_osse_eligibility
    features:
      - key: :broker_quote_osse_eligibility
        item: :broker_quote_osse_eligibility
        is_enabled: <%= ENV['BROKER_QUOTE_HC4CC_SUBSIDY_IS_ENABLED'] || false %>
      - key: :aca_shop_osse_eligibility_2021
        item: :osse_eligibility_criterion
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_2021_IS_ENABLED'] || false %>
      - key: :aca_shop_osse_eligibility_2022
        item: :osse_eligibility_criterion
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_2022_IS_ENABLED'] || false %>
        settings:
          - key: :grants_offered
            item:
              - :minimum_participation_rule_relaxed_2022
              - :all_contribution_levels_min_met_relaxed_2022
              - :benefit_application_fte_count_relaxed_2022
              - :employer_metal_level_products_restricted_2022
      - key: :aca_shop_osse_eligibility_2023
        item: :osse_eligibility_criterion
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_2023_IS_ENABLED'] || false %>
        settings:
        - key: :grants_offered
          item:
            - :minimum_participation_rule_relaxed_2023
            - :all_contribution_levels_min_met_relaxed_2023
            - :benefit_application_fte_count_relaxed_2023
            - :employer_metal_level_products_restricted_2023
      - key: :aca_shop_osse_eligibility_2024
        item: :osse_eligibility_criterion
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_2024_IS_ENABLED'] || false %>
        settings:
        - key: :grants_offered
          item:
            - :minimum_participation_rule_relaxed_2024
            - :all_contribution_levels_min_met_relaxed_2024
            - :benefit_application_fte_count_relaxed_2024
            - :employer_metal_level_products_restricted_2024
      - key: :aca_shop_osse_eligibility_2025
        item: :osse_eligibility_criterion
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_2025_IS_ENABLED'] || false %>
        settings:
        - key: :grants_offered
          item:
            - :minimum_participation_rule_relaxed_2025
            - :all_contribution_levels_min_met_relaxed_2025
            - :benefit_application_fte_count_relaxed_2025
            - :employer_metal_level_products_restricted_2025
  
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :aca_shop_osse_eligibility
    - :aca_shop_osse_eligibility_2022
    features:
      - key: :minimum_participation_rule_relaxed_2022
        item: minimum_participation_rule
        is_enabled: true
      - key: :all_contribution_levels_min_met_relaxed_2022
        item: 'all_contribution_levels_min_met'
        is_enabled: false
      - key: :benefit_application_fte_count_relaxed_2022
        item: 'benefit_application_fte_count'
        is_enabled: false
      - key: :employer_metal_level_products_restricted_2022
        item: 'employer_metal_level_products'
        is_enabled: false
      - key: :lowest_cost_silver_product_2022
        item: '94506DC0350030-01'
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_2022_IS_ENABLED'] || false %>
 
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :aca_shop_osse_eligibility
    - :aca_shop_osse_eligibility_2023
    features:
      - key: :minimum_participation_rule_relaxed_2023
        item: minimum_participation_rule
        is_enabled: true
      - key: :all_contribution_levels_min_met_relaxed_2023
        item: 'all_contribution_levels_min_met'
        is_enabled: true
      - key: :benefit_application_fte_count_relaxed_2023
        item: 'benefit_application_fte_count'
        is_enabled: true
      - key: :employer_metal_level_products_restricted_2023
        item: 'employer_metal_level_products'
        is_enabled: true
      - key: :lowest_cost_silver_product_2023
        item: '94506DC0350033-01'
        is_enabled: <%= ENV['SHOP_OSSE_ELIGIBILITY_2023_IS_ENABLED'] || false %>

  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :aca_shop_osse_eligibility
    - :aca_shop_osse_eligibility_2024
    features:
      - key: :minimum_participation_rule_relaxed_2024
        item: minimum_participation_rule
        is_enabled: true
      - key: :all_contribution_levels_min_met_relaxed_2024
        item: 'all_contribution_levels_min_met'
        is_enabled: true
      - key: :benefit_application_fte_count_relaxed_2024
        item: 'benefit_application_fte_count'
        is_enabled: true
      - key: :employer_metal_level_products_restricted_2024
        item: 'employer_metal_level_products'
        is_enabled: true
      - key: :lowest_cost_silver_product_2024
        item: '94506DC0350032-01'
        is_enabled: true
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :aca_shop_osse_eligibility
    - :aca_shop_osse_eligibility_2025
    features:
      - key: :minimum_participation_rule_relaxed_2025
        item: minimum_participation_rule
        is_enabled: true
      - key: :all_contribution_levels_min_met_relaxed_2025
        item: 'all_contribution_levels_min_met'
        is_enabled: true
      - key: :benefit_application_fte_count_relaxed_2025
        item: 'benefit_application_fte_count'
        is_enabled: true
      - key: :employer_metal_level_products_restricted_2025
        item: 'employer_metal_level_products'
        is_enabled: true
      - key: :lowest_cost_silver_product_2025
        item: '94506DC0350032-01'
        is_enabled: true
