registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    features:
      - key: :waived_members_eligiblity
        item: :waived_members_eligiblity
        is_enabled: true
      - key: :send_secure_message_employer
        item: :send_secure_message
        is_enabled: true
      - key: :benefit_application_reinstate
        item: BenefitSponsors::Operations::BenefitApplications::Reinstate.new
        is_enabled: true
        settings:
           - key: :offset_months
             item: 0
