version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/development/Dockerfile
      args:
        BUNDLER_VERSION_OVERRIDE: '2.0.1'
        NODE_MAJOR: '10'
        YARN_VERSION: '1.22.4'
    image: enroll:dev-0.1.0
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/enroll:cached
      - bundle:/bundle
      - node_modules:/enroll/node_modules
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DB_DATABASE=enroll_development
      - DB_USERNAME=enroll
      - DB_PASSWORD=enroll_local
      - DB_HOST=db
      - DB_PORT=27017
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-AKIA123456789}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-AbcD987654321}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_ROOT_NAMESPACE=${AWS_S3_ROOT_NAMESPACE:-root_bucket}
      - AWS_BUCKET_ROOT_NAMESPACE=${AWS_BUCKET_ROOT_NAMESPACE:-root_bucket}
      - ACTION_MAILER_HOST=${ACTION_MAILER_HOST:-localhost}
      - HBX_ID=${HBX_ID:-dc0}
      - ENV_NAME=${ENV_NAME:-dev}
      - ACAPI_BROKER_HOST=${ACAPI_BROKER_HOST:-amqp}
      - ACAPI_BROKER_PORT=${ACAPI_BROKER_PORT:-5672}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@amqp:5672}
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && yarn install --check-files && bundle install && bundle exec puma -C config/puma.rb"
  remote_event_listener:
    image: enroll:dev-0.1.0
    ports:
      - 3000
    links:
      - db
    volumes:
      - .:/enroll:cached
      - bundle:/bundle
      - node_modules:/enroll/node_modules
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DB_DATABASE=enroll_development
      - DB_USERNAME=enroll
      - DB_PASSWORD=enroll_local
      - DB_HOST=db
      - DB_PORT=27017
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-AKIA123456789}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-AbcD987654321}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_ROOT_NAMESPACE=${AWS_S3_ROOT_NAMESPACE:-root_bucket}
      - AWS_BUCKET_ROOT_NAMESPACE=${AWS_BUCKET_ROOT_NAMESPACE:-root_bucket}
      - ACTION_MAILER_HOST=${ACTION_MAILER_HOST:-localhost}
      - HBX_ID=${HBX_ID:-dc0}
      - ENV_NAME=${ENV_NAME:-dev}
      - ACAPI_BROKER_HOST=${ACAPI_BROKER_HOST:-amqp}
      - ACAPI_BROKER_PORT=${ACAPI_BROKER_PORT:-5672}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@amqp:5672}
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && yarn install --check-files && bundle install && bundle exec rails runner script/remote_event_listener.rb"
  db:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/db_config
    ports:
      - 27017:27017
  amqp:
    build:
      context: .
      dockerfile: ./.docker/development/Dockerfile.rabbitmq
      args:
        - HBX_ID=${HBX_ID:-dc0}
        - ENV_NAME=${ENV_NAME:-dev}
    image: ideacrew/enroll_amqp:dev-0.1.0
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-123456789}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - 4369
      - 5672:5672
      - 25672:25672
      - 15672:15672
volumes:
  mongodb:
  mongodb_config:
  bundle:
  node_modules:
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs:
