registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    features:
      - key: :waived_members_eligiblity
        item: :waived_members_eligiblity
        is_enabled: true
      - key: :send_secure_message_employer
        item: :send_secure_message
        is_enabled: true
      - key: :verify_quiet_period_after_application_effectuated
        is_enabled: false
      - key: :benefit_application_reinstate
        item: BenefitSponsors::Operations::BenefitApplications::Reinstate.new
        is_enabled: false
        settings:
           - key: :offset_months
             item: 0
      - key: :employer_profile_class
        item: :employer_profile_class
        is_enabled: true
        settings:
          - key: :class_name
            item: "BenefitSponsors::Organizations::AcaShopMeEmployerProfile"
      - key: :disable_benefit_application_date_message
        item: :disable_benefit_application_date_message
        is_enabled: true
      - key: :coverage_should_start_in
        item: :coverage_should_start_in
        is_enabled: true
        settings:
          - key: :time_from_now
            item: "In the next 90 days"
      - key: :census_employee_roster
        item: :census_employee_roster
        is_enabled: true
        settings:
          - key: :roster_upload_file_name
            item: "Health Connector - Employee Census Template.xlsx"
      - key: :sic_codes
        item: :sic_codes
        is_enabled: false
      - key: :county_zips
        item: :county_zips
        is_enabled: false
      - key: :employer_datatable_source_kinds
        item: :employer_datatable_source_kinds
        is_enabled: false
      - key: :employer_attestation
        item: :employer_attestation
        is_enabled: false
      - key: :cobra_enrollment_period
        item: :cobra_enrollment_period
        is_enabled: true
        settings:
          - key: :months
            item: 6
      - key: :prior_plan_year_shop_sep
        is_enabled: false
        item: Operations::GeneratePriorPlanYearShopRenewals.new
        settings:
          - key: :offset_months
            item: 12
      - key: :admin_shop_end_date_changes
        is_enabled: false
