---
registry:
  - namespace:
    - :enroll_app
    - :aca_individual_market
    - :financial_assistance
    features:
      - key: :aceds_curam
        item: :aceds_curam
        is_enabled: false
      - key: :ivl_application_checklist
        is_enabled: false
        item: :ivl_application_checklist
        settings:
          - key: :file_location
            item: 'db/documents/ivl_checklist_me.pdf'
      - key: :iap_year_selection
        is_enabled: false
      - key: :iap_assistance_year_display
        is_enabled: false
      - key: :enrollment_dates
        item: :enrollment_dates
        is_enabled: true
        settings:
          - key: :application_new_year_effective_date_day_of_month
            item: 19
          - key: :application_new_year_effective_date_month_of_year
            item: 9
          - key: :enrollment_due_day_of_month
            is_enabled: true
            item: 15
          - key: :earliest_effective_date
            item: FinancialAssistance::Operations::EnrollmentDates::EarliestEffectiveDate
            is_enabled: true
          - key: :application_year
            item: FinancialAssistance::Operations::EnrollmentDates::ApplicationYear
            is_enabled: true
      - key: :benchmark_plans
        item: :benchmark_plans
        is_enabled: true
        settings:
          - key: :benchmark_plan_2020
            item: true
            settings:
              - key: :name
                item: 'Plan Name'
              - key: :hios_id
                item: 'HIOS-ID'
              - key: :is_dental_only
                item: false
              - key: :metal_level
                item: :silver
              - key: :coverage_kind
                item: :health
              - key: :ehb
                item: 0.80
              - key: :carrier_name
                item: "Carrier Name"
      - key: :unemployment_income
        item: :unemployment_income
        is_enabled: true
      - key: :medicaid_tax_credits_link
        item: :medicaid_tax_credits_link
        is_enabled: false
      - key: :primary_caregiver_other_question
        item: :primary_caregiver_other_question
        is_enabled: true
      - key: :american_indian_alaskan_native_income
        item: :american_indian_alaskan_native_income
        is_enabled: true
      - key: :indian_health_service_question
        is_enabled: true
      - key: :mainecare_healthcare_questions
        is_enabled: true
      - key: :immigration_status_question_required
        is_enabled: false
      - key: :mec_check
        is_enabled: true
      - key: :include_faa_outstanding_verifications
        is_enabled: true
  - namespace:
    - :request_determination
    features:
    - key: :haven_determination
      is_enabled: false
    - key: :medicaid_gateway_determination
      is_enabled: true
    - key: :esi_mec_determination
      is_enabled: true
    - key: :non_esi_mec_determination
      is_enabled: true
    - key: :ifsv_determination
      is_enabled: true
  - namespace:
    - :account_transfer
    features:
    - key: :real_time_transfer
      is_enabled: false
    - key: :batch_transfer
      is_enabled: true
    - key: :transfer_service
      is_enabled: true
      item: "aces"
  - namespace:
    - :documents
    features:
      - key: :consumer_validations
        is_enabled: true
      - key: :non_magi_referral_display
        is_enabled: true
  - namespace:
    - :questions
    features:
    - key: :has_enrolled_health_coverage
      is_enabled: true
      settings:
        - key: :currently_enrolled
          item: false
        - key: :currently_enrolled_with_hra
          item: true
    - key: :has_eligible_health_coverage
      is_enabled: true
      settings:
        - key: :currently_eligible
          item: false
        - key: :currently_eligible_with_hra
          item: true
    - key: :has_medicare_cubcare_eligible
      is_enabled: true
    - key: :medicaid_chip_driver_questions
      is_enabled: true
      settings:
        - key: :medicaid_chip
          item: "Medicaid"
    - key: :net_annual_income_display
      is_enabled: true
    - key: :has_dependent_with_coverage
      is_enabled: true
    - key: :private_individual_and_family_coverage
      is_enabled: true
    - key: :acf_refugee_medical_assistance
      is_enabled: false
    - key: :americorps_health_benefits
      is_enabled: false
    - key: :child_health_insurance_plan
      is_enabled: true
    - key: :medicaid
      is_enabled: true
    - key: :medicare
      is_enabled: true
    - key: :medicare_advantage
      is_enabled: false
    - key: :medicare_part_b
      is_enabled: false
    - key: :state_supplementary_payment
      is_enabled: false
    - key: :tricare
      is_enabled: true
    - key: :veterans_benefits
      is_enabled: false
    - key: :naf_health_benefit_program
      is_enabled: false
    - key: :health_care_for_peace_corp_volunteers
      is_enabled: false
    - key: :department_of_defense_non_appropriated_health_benefits
      is_enabled: false
    - key: :cobra_benefit_fa
      is_enabled: true
    - key: :employer_sponsored_insurance
      is_enabled: true
    - key: :self_funded_student_health_coverage
      is_enabled: false
    - key: :foreign_government_health_coverage
      is_enabled: false
    - key: :private_health_insurance_plan
      is_enabled: false
    - key: :coverage_obtained_through_another_exchange
      is_enabled: true
    - key: :coverage_under_the_state_health_benefits_risk_pool
      is_enabled: false
    - key: :veterans_administration_health_benefits
      is_enabled: true
    - key: :peace_corps_health_benefits
      is_enabled: true
    - key: :health_reimbursement_arrangement # new
      is_enabled: true
    - key: :retiree_health_benefits # new
      is_enabled: true
    - key: :other_full_benefit_coverage # new
      is_enabled: true
    - key: :other_limited_benefit_coverage # new
      is_enabled: true
    - key: :prize_and_awards
      is_enabled: true
      settings:
        - key: :gamble_prize
          item: true
    - key: :full_medicaid_determination_step
      is_enabled: false
    - key: :native_american_csr
      is_enabled: true
    - key: :display_medicaid_question
      item: :display_medicaid_question
      is_enabled: false
    - key: :optional_document_fields
      item: :optional_document_fields
      is_enabled: true
    - key: :disable_employer_address_fields
      item: :disable_employer_address_fields
      is_enabled: true
    - key: :fa_send_to_external_verification
      is_enabled: true
    - key: :medicaid_or_chip_program_short_name
      is_enabled: true
      settings:
        - key: :name
          item: "MaineCare or Cub Care"
    - key: :medicaid_or_chip_agency_long_name
      is_enabled: true
      settings:
        - key: :name
          item: 'Office for Family Independence'
    - key: :student_follow_up_questions
      is_enabled: false
    - key: :filing_as_head_of_household
      is_enabled: true
    - key: :no_coverage_tribe_details
      is_enabled: true
    - key: :pregnancy_due_on_required
      is_enabled: false
    - key: :voter_registration_through_ext_url
      is_enabled: true
    - key: :voter_registration_through_hbx
      is_enabled: false
    - key: :question_required
      is_enabled: false
  - namespace:
    - :renewals
    features:
    - key: :create_renewals_on_date_change
      is_enabled: false
      settings:
        - key: :renewals_creation_month
          item: 10
        - key: :renewals_creation_day
          item: 16
    - key: :skip_employer_address_validation
      is_enabled: :true
    - key: :skip_employer_phone_validation
      is_enabled: :true
    - key: :skip_employer_id_validation
      is_enabled: :true
    - key: :negative_amount_income_types
      is_enabled: true
      settings:
        - key: :income_types
          item: ["net_self_employment", "capital_gains", "farming_and_fishing", "rental_and_royalty", "other"]
    - key: :skip_zero_income_amount_validation
      is_enabled: :true
    - key: :job_income_warning_message
      item: :job_income_warning_message
      is_enabled: true
# TODO eligibility engine connectivity(HAVEN) settings
# TODO mec service connectivity settings
