
site:
  short_name: "Be Well NM"
  long_name: ""

  call_center: 
    name: "Be Well NM's Customer Care Center"
    phone_number: "1-855-532-5465"

aca:
  state_name: "District of Columbia"
  state_abbreviation: "DC"
  ivl: 
    enrollment_due_day_of_month: 15
  shop:
    retroactive_termination_maximum: 60.days
    renewal_period_before_start_on_maximum: 3.months
