site:
  aca_market_kinds: ["individual", "shop"]
  general_agency_enabled: true
  registration_path: ""

aca:

  shop_market:
    employee_participation_ratio_minimum: <%= 2 / 3.0 %>
    binder_payment_due_on: 12

    initial_application:
      publish_due_day_of_month: 5
      earliest_start_prior_to_effective_on:
        months: -3

    renewal_application:
      earliest_start_prior_to_effective_on:
        months: -3
      monthly_open_enrollment_end_on: 13
      publish_due_day_of_month: 10
      force_publish_day_of_month: 11
      open_enrollment:
        minimum_length:
          days: 3

    open_enrollment:
      monthly_start_on: 1
      monthly_end_on: 10
