registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    features:
      - key: :waived_members_eligiblity
        item: :waived_members_eligiblity
        is_enabled: true
      - key: :send_secure_message_employer
        item: :send_secure_message
        is_enabled: true
      - key: :employee_registration
        item: :employee_role
        is_enabled: true
      - key: :employer_registration
        item: BenefitSponsors::Operations::Employers::Create.new
        is_enabled: true
      - key: :employer_staff_registration
        item: BenefitSponsors::Operations::Employers::AddEmployerStaff.new
        is_enabled: true
      - key: :broker_registration
        item: BenefitSponsors::Operations::BrokerAgencies::Create.new
        is_enabled: true
      - key: :broker_staff_registration
        item: BenefitSponsors::Operations::BrokerAgencies::AddBrokerAgencyStaff.new
        is_enabled: true
      - key: :ga_registration
        item: BenefitSponsors::Operations::GeneralAgencies::Create.new
        is_enabled: true
      - key: :ga_staff_registration
        item: BenefitSponsors::Operations::GeneralAgencies::AddGeneralAgencyStaff.new
        is_enabled: true
      - key: :benefit_application_reinstate
        item: BenefitSponsors::Operations::BenefitApplications::Reinstate.new
        is_enabled: true
        settings:
           - key: :offset_months
             item: 0
      - key: :employer_profile_class
        item: :employer_profile_class
        is_enabled: true
        settings:
          - key: :class_name
            item: "BenefitSponsors::Organizations::AcaShopDcEmployerProfile"
      - key: :disable_benefit_application_date_message
        item: :disable_benefit_application_date_message
        is_enabled: true
      - key: :coverage_should_start_in
        item: :coverage_should_start_in
        is_enabled: true
        settings:
          - key: :time_from_now
            item: "In the next 90 days"
      - key: :census_employee_roster
        item: :census_employee_roster
        is_enabled: true
        settings:
          - key: :roster_upload_file_name
            item: "Health Connector - Employee Census Template.xlsx"
      - key: :sic_codes
        item: :sic_codes
        is_enabled: false
      - key: :county_zips
        item: :county_zips
        is_enabled: false
      - key: :general_agency
        item: :general_agency
        is_enabled: true
      - key: :employer_datatable_source_kinds
        item: :employer_datatable_source_kinds
        is_enabled: false
      - key: :employer_attestation
        item: :employer_attestation
        is_enabled: false
