---
registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    features:
      - key: :contribution_model_aca_shop
        item: BenefitMarkets::Operations::ContributionModels::Create.new
        is_enabled: true
      - key: :assign_contribution_model_aca_shop
        item: BenefitMarkets::Operations::ContributionModels::Assign.new
        is_enabled: true

  - namespace:
    - :enroll_app
    - :fehb_market
    - :benefit_market_catalog
    features:
      - key: :contribution_model_fehb
        item: BenefitMarkets::Operations::ContributionModels::Create.new
        is_enabled: true
      - key: :assign_contribution_model_fehb
        item: BenefitMarkets::Operations::ContributionModels::Assign.new
        is_enabled: false

  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :catalog_2019
    - :contribution_model_criteria
    features:
      - key: :initial_sponsor_jan_default_2019
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2019,1,1)..Date.new(2019,1,31) %>
          - key: :order
            item: 1
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :initial_sponsor_jan_default
      - key: :initial_sponsor_default_2019
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :fifty_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2019,2,1)..Date.new(2019,12,31) %>
          - key: :order
            item: 3
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :initial_sponsor_default
      - key: :renewal_sponsor_jan_default_2019
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2019,1,1)..Date.new(2019,1,31) %>
          - key: :order
            item: 4
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :renewal_sponsor_jan_default
      - key: :renewal_sponsor_default_2019
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :fifty_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2019,2,1)..Date.new(2019,12,31) %>
          - key: :order
            item: 2
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :renewal_sponsor_default
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :catalog_2020
    - :contribution_model_criteria
    features:
      - key: :initial_sponsor_jan_default_2020
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2020,1,1)..Date.new(2020,1,31) %>
          - key: :order
            item: 1
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :initial_sponsor_jan_default
      - key: :initial_sponsor_default_2020
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2020,2,1)..Date.new(2020,12,31) %>
          - key: :order
            item: 3
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :initial_sponsor_default
      - key: :renewal_sponsor_jan_default_2020
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2020,1,1)..Date.new(2020,1,31) %>
          - key: :order
            item: 4
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :renewal_sponsor_jan_default
      - key: :renewal_sponsor_default_2020
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :fifty_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2020,2,1)..Date.new(2020,12,31) %>
          - key: :order
            item: 2
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :renewal_sponsor_default
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :catalog_2021
    - :contribution_model_criteria
    features:
      - key: :initial_sponsor_jan_default_2021
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2021,1,1)..Date.new(2021,1,31) %>
          - key: :order
            item: 1
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :initial_sponsor_jan_default
      - key: :initial_sponsor_default_2021
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :initial
          - key: :effective_period
            item: <%= Date.new(2021,2,1)..Date.new(2021,12,31) %>
          - key: :order
            item: 3
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :initial_sponsor_default
      - key: :renewal_sponsor_jan_default_2021
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2021,1,1)..Date.new(2021,1,31) %>
          - key: :order
            item: 4
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :renewal_sponsor_jan_default
      - key: :renewal_sponsor_default_2021
        item: :contribution_model_criterion
        is_enabled: true
        settings:
          - key: :contribution_model_key
            item: :fifty_percent_sponsor_fixed_percent_contribution_model
          - key: :benefit_application_kind
            item: :renewal
          - key: :effective_period
            item: <%= Date.new(2021,2,1)..Date.new(2021,12,31) %>
          - key: :order
            item: 2
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :renewal_sponsor_default
  - namespace:
      - :enroll_app
      - :aca_shop_market
      - :benefit_market_catalog
      - :catalog_2020
    features:
      - key: :aca_shop_fetch_enrollment_minimum_participation_2020
        item: BenefitMarkets::Operations::BenefitSponsorCatalogs::FetchMinimumParticipation.new
        is_enabled: true
        settings:
          - key: :zero_percent_sponsor_fixed_percent_contribution_model
            item: 0
          - key: :fifty_percent_sponsor_fixed_percent_contribution_model
            item: <%= 2 / 3.0 %>
      - key: :fehb_fetch_enrollment_minimum_participation_2020
        item: BenefitMarkets::Operations::BenefitSponsorCatalogs::FetchMinimumParticipation.new
        is_enabled: false
        settings:
          - key: :zero_percent_sponsor_fixed_percent_contribution_model
            item: 0
          - key: :fifty_percent_sponsor_fixed_percent_contribution_model
            item: <%= 2 / 3.0 %>
  - namespace:
      - :enroll_app
      - :aca_shop_market
      - :benefit_market_catalog
      - :catalog_2019
    features:
      - key: :aca_shop_fetch_enrollment_minimum_participation_2019
        item: BenefitMarkets::Operations::BenefitSponsorCatalogs::FetchMinimumParticipation.new
        is_enabled: true
        settings:
          - key: :zero_percent_sponsor_fixed_percent_contribution_model
            item: 0
          - key: :fifty_percent_sponsor_fixed_percent_contribution_model
            item: <%= 2 / 3.0 %>
      - key: :fehb_fetch_enrollment_minimum_participation_2019
        item: BenefitMarkets::Operations::BenefitSponsorCatalogs::FetchMinimumParticipation.new
        is_enabled: false
        settings:
          - key: :zero_percent_sponsor_fixed_percent_contribution_model
            item: 0
          - key: :fifty_percent_sponsor_fixed_percent_contribution_model
            item: <%= 2 / 3.0 %>

  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :broker_quoting_tool
    features:
      - key: :flexible_contribution_model_for_bqt
        item: :contribution_model
        is_enabled: true
        settings:
        - key: :initial_application_period
          item: <%= Date.new(2020,03,01)..Date.new(2020,12,31) %>
        - key: :enabled_for_renewal_applications
          item: false
        - key: :employer_contribution_percent_minimum
          item: 0
        - key: :employer_family_contribution_percent_minimum
          item: 0

  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :initial_application
    features:
      - key: :flexible_contribution_model_for_initials
        item: :contribution_model
        is_enabled: true
        settings:
        - key: :application_period
          item: <%= Date.new(2020,03,01)..Date.new(2020,12,31) %>
        - key: :employee_participation_ratio_minimum
          item: 0