---
registry:
  - namespace:
      - :enroll_app
    features:
      - key: :hbx_admin_config
        is_enabled: true
  - namespace:
    - :enroll_app
    - :hbx_admin_config
    features:
        - key: :issuers_tab
          is_enabled: true
        - key: :inbox_tab
          is_enabled: true
        - key: :notices_tab
          is_enabled: true
        - key: :staff_tab
          is_enabled: true
        - key: :orphan_accounts_tab
          is_enabled: true
        - key: :no_transition_families
          is_enabled: true
        - key: :drop_enrollment_members
          is_enabled: false
        - key: :drop_retro_scenario
          is_enabled: <%= ENV['RETRO_FEATURE_IS_ENABLED'] || false %>
        - key: :resend_broker_email_button
          is_enabled: <%= ENV['RESEND_BROKER_EMAIL_BUTTON_IS_ENABLED'] || false %>
        - key: :admin_account_autolock
          is_enabled: <%= ENV['ADMIN_ACCOUNT_AUTOLOCK_IS_ENABLED'] || false %>
