---
registry:
  - namespace:
      - :fdsh_services
    features:
      - key: :ridp_h139
        is_enabled: true
        settings:
          - key: :payload_format
            item: <%= ENV['RIDP_H139_PAYLOAD_FORMAT'] || "xml" %>
      - key: :paper_application_verification
        is_enabled: true
      - key: :vlp_h92
        is_enabled: true
        settings:
          - key: :payload_type
            item: <%= ENV['VLP_PAYLOAD_TYPE'] || "xml" %>
      - key: :vlp_rx142
        is_enabled: true
        settings:
          - key: :payload_type
            item: <%= ENV['VLP_RX142_PAYLOAD_TYPE'] || "xml" %>
      - key: :ssa_h3
        is_enabled: true
        settings:
        - key: :payload_type
          item:  <%= ENV['SSA_H3_PAYLOAD_TYPE'] || "xml" %>
        - key: :use_transmittable
          item: <%= ENV['SSA_H3_USE_TRANSMITTABLE'] || false %>
      - key: :non_esi_h31
        is_enabled: true
        settings:
        - key: :payload_format
          item: <%= ENV['NON_ESI_H31_PAYLOAD_FORMAT'] || "xml" %>
      - key: :esi_mec
        is_enabled: true
        settings:
          - key: :payload_format
            item: <%= ENV['ESI_MEC_PAYLOAD_FORMAT'] || "xml" %>
      - key: :ifsv
        is_enabled: true
        settings:
          - key: :payload_format
            item: <%= ENV['IFSV_PAYLOAD_FORMAT'] || "xml" %>
      - key: :renewal_eligibility_verification_using_rrv
        item: :renewal_eligibility_verification_using_rrv
        is_enabled: <%= ENV['RENEWAL_ELIGIBILITY_VERIFICATION_USING_RRV_IS_ENABLED'] || false %>
      - key: :validate_and_record_publish_errors
        is_enabled: <%= ENV['VALIDATE_AND_RECORD_PUBLISH_ERRORS_IS_ENABLED'] || false %>
      - key: :validate_and_record_publish_application_errors
        is_enabled: <%= ENV['VALIDATE_AND_RECORD_PUBLISH_APPLICATION_ERRORS_IS_ENABLED'] || false %>
      - key: :send_close_case_request
        item: :send_close_case_request
        is_enabled: <%= ENV['SEND_CLOSE_CASE_REQUEST_IS_ENABLED'] || false %>
      - key: :show_new_documents_tab_text
        is_enabled: <%= ENV['SHOW_NEW_DOCUMENTS_TAB_TEXT'] || false %>
      
