---
registry:
  - namespace:
      - :enroll_app
    features:
      - key: :hbx_admin_config
        is_enabled: true
  - namespace:
    - :enroll_app
    - :hbx_admin_config
    features:
        - key: :issuers_tab
          is_enabled: true
        - key: :inbox_tab
          is_enabled: true
        - key: :notices_tab
          is_enabled: true
        - key: :calendar_tab
          is_enabled: true
        - key: :staff_tab
          is_enabled: true
        - key: :orphan_accounts_tab
          is_enabled: true
        - key: :no_transition_families
          is_enabled: true
        - key: :drop_enrollment_members
          is_enabled: false
